# Generated by Django 3.2.3 on 2021-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lion', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=300)),
                ('refresh_token', models.CharField(max_length=300)),
            ],
        ),
    ]
