# Generated by Django 3.2.3 on 2021-05-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0002_accesstokens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessTokens',
        ),
    ]
