# Generated by Django 3.2.3 on 2021-05-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0005_auto_20210521_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpages',
            name='category_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
