# Generated by Django 3.2.3 on 2021-05-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0006_facebookpages_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookpages',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='facebookpages',
            name='category',
            field=models.JSONField(null=True),
        ),
    ]
