# Generated by Django 3.2.3 on 2021-05-21 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('tiger', '0007_auto_20210521_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fb_user', to='socialaccount.socialaccount'),
        ),
    ]
