# Generated by Django 3.2.3 on 2021-05-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0009_auto_20210521_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookpages',
            old_name='user_fb',
            new_name='user',
        ),
    ]
